language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "pypy"
install:
  - if [[ $TRAVIS_PYTHON_VERSION == 2.6 ]]; then pip install -r py26-requirements.txt; fi
  - pip install -r requirements.txt
  - pip install coveralls
script:
  - nosetests --with-coverage --cover-erase --cover-package=times2
after_success:
  - coveralls
